import './globals.scss'
import '@/assets/scss/fonts.scss'
import '@/assets/scss/custom-scrollbar.scss'
import '@/assets/scss/index.scss'
import '@/assets/scss/tailwind.scss'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { AuthContainer } from '@/components/features/auth-provider'
import { UserAvatarNav } from '@/components/features/user-nav'
import { Logo } from '@/components/shared/logo'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Meety',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <AuthContainer>
      <html lang="en">
        <body className={inter.className}>
          <header className="flex h-95 items-center justify-between border-b border-white/20 px-40 py-15">
            <Logo />
            <UserAvatarNav />
          </header>
          <main className="pb-40 pt-25">{children}</main>
        </body>
      </html>
    </AuthContainer>
  )
}
