import type { Metadata } from 'next'

import { LadderTablePreview } from '@/components/widgets/ladder'
import { ProfileUserBanner } from '@/components/widgets/profile'

export const metadata: Metadata = {
  title: 'Meety',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <div className="container">
      <div className="grid grid-cols-[calc(100%-380px-25px)_380px] gap-x-25">
        <section className="flex flex-col gap-y-25">
          <ProfileUserBanner></ProfileUserBanner>
          <div>{children}</div>
        </section>

        <section>
          <LadderTablePreview />
        </section>
      </div>
    </div>
  )
}
